set_cookies requires a string
This was causing:

```
/home/steven/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http/header.rb:17:in `block in initialize_http_header': undefined method `strip' for nil:NilClass (NoMethodError)
```

after logging out of one account and into another, since the cookies weren't a string.